name: PR update checks
on:
  pull_request:
    branches:
      - main

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/run_checks_suite.yml
    secrets: inherit
  checkmark:
    runs-on: ubuntu-latest
    needs: [checks]
    if: ${{ !cancelled() }}
    steps:
      - name: All jobs ok
        if: ${{ success() || !contains(needs.*.result, 'failure') }}
        run: exit 0
      - name: One or more jobs failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: debug-print
        if: ${{ !cancelled() }}
        run: |
          echo "toJSON(needs) = ${{ toJSON(needs) }}"
          echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"
